package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IllustratorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIllustratorAllPropertiesEquals(Illustrator expected, Illustrator actual) {
        assertIllustratorAutoGeneratedPropertiesEquals(expected, actual);
        assertIllustratorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIllustratorAllUpdatablePropertiesEquals(Illustrator expected, Illustrator actual) {
        assertIllustratorUpdatableFieldsEquals(expected, actual);
        assertIllustratorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIllustratorAutoGeneratedPropertiesEquals(Illustrator expected, Illustrator actual) {
        assertThat(actual)
            .as("Verify Illustrator auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIllustratorUpdatableFieldsEquals(Illustrator expected, Illustrator actual) {
        assertThat(actual)
            .as("Verify Illustrator relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIllustratorUpdatableRelationshipsEquals(Illustrator expected, Illustrator actual) {
        // empty method
    }
}
