package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineAllPropertiesEquals(OrderLine expected, OrderLine actual) {
        assertOrderLineAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineAllUpdatablePropertiesEquals(OrderLine expected, OrderLine actual) {
        assertOrderLineUpdatableFieldsEquals(expected, actual);
        assertOrderLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineAutoGeneratedPropertiesEquals(OrderLine expected, OrderLine actual) {
        assertThat(actual)
            .as("Verify OrderLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineUpdatableFieldsEquals(OrderLine expected, OrderLine actual) {
        assertThat(actual)
            .as("Verify OrderLine relevant properties")
            .satisfies(a -> assertThat(a.getUnitPrice()).as("check unitPrice").isEqualTo(expected.getUnitPrice()))
            .satisfies(a -> assertThat(a.getTotal()).as("check total").isEqualTo(expected.getTotal()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineUpdatableRelationshipsEquals(OrderLine expected, OrderLine actual) {
        assertThat(actual)
            .as("Verify OrderLine relationships")
            .satisfies(a -> assertThat(a.getProdOrder()).as("check prodOrder").isEqualTo(expected.getProdOrder()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
