package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PayementTunnelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayementTunnelAllPropertiesEquals(PayementTunnel expected, PayementTunnel actual) {
        assertPayementTunnelAutoGeneratedPropertiesEquals(expected, actual);
        assertPayementTunnelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayementTunnelAllUpdatablePropertiesEquals(PayementTunnel expected, PayementTunnel actual) {
        assertPayementTunnelUpdatableFieldsEquals(expected, actual);
        assertPayementTunnelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayementTunnelAutoGeneratedPropertiesEquals(PayementTunnel expected, PayementTunnel actual) {
        assertThat(actual)
            .as("Verify PayementTunnel auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayementTunnelUpdatableFieldsEquals(PayementTunnel expected, PayementTunnel actual) {
        assertThat(actual)
            .as("Verify PayementTunnel relevant properties")
            .satisfies(a -> assertThat(a.getPayementMethod()).as("check payementMethod").isEqualTo(expected.getPayementMethod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayementTunnelUpdatableRelationshipsEquals(PayementTunnel expected, PayementTunnel actual) {
        // empty method
    }
}
