package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProdOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdOrderAllPropertiesEquals(ProdOrder expected, ProdOrder actual) {
        assertProdOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertProdOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdOrderAllUpdatablePropertiesEquals(ProdOrder expected, ProdOrder actual) {
        assertProdOrderUpdatableFieldsEquals(expected, actual);
        assertProdOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdOrderAutoGeneratedPropertiesEquals(ProdOrder expected, ProdOrder actual) {
        assertThat(actual)
            .as("Verify ProdOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdOrderUpdatableFieldsEquals(ProdOrder expected, ProdOrder actual) {
        assertThat(actual)
            .as("Verify ProdOrder relevant properties")
            .satisfies(a -> assertThat(a.getValid()).as("check valid").isEqualTo(expected.getValid()))
            .satisfies(a -> assertThat(a.getPromo()).as("check promo").isEqualTo(expected.getPromo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdOrderUpdatableRelationshipsEquals(ProdOrder expected, ProdOrder actual) {
        assertThat(actual)
            .as("Verify ProdOrder relationships")
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }
}
